GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJEYWZmYSBBZmRhbGxhaCIsImVtYWlsIjoiZGFmZmFAZ21haWwuY29tIiwiaWF0IjoxNzE4ODU4MDUyLCJleHAiOjE3MTg4NTgwNjd9.-UnKbrVNefxZ80H0yHFYwshBODV6Qz6s9jQrTevimsU


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Daffa Afdallah",
    "email": "daffa@gmail.com",
    "password": "daffa123",
    "confPassword": "daffa123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "daffa@gmail.com",
    "password": "daffa123"
}

###
GET http://localhost:5000/token